
[[constraint]]
  name = "github.com/nats-io/go-nats-streaming"
  version = "0.4.0"

[[constraint]]
  name = "github.com/openfaas/faas"
  version = "0.9.9"

[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "v1.5.0"

[[constraint]]
  name = "github.com/openfaas/faas-provider"
  version = "0.7.1"

[prune]
  go-tests = true
  unused-packages = true
