#[[constraint]]
#  name = "github.com/nats-io/stan.go"
#  version = "0.6.0"

[[constraint]]
  name = "github.com/openfaas/faas"
  version = "0.18.16"

[[constraint]]
  name = "github.com/openfaas/faas-provider"
  version = "0.7.0"

[[constraint]]
  name = "github.com/nats-io/stan.go"
  version = "0.6.0"


[prune]
  go-tests = true
  unused-packages = true
